INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "/data/raid_ssd/schoerob/simple_click/models/model_1112_2022"

# Evaluation datasets
GRABCUT_PATH: "/data/raid_ssd/schoerob/GrabCut"
BERKELEY_PATH: "/data/raid_ssd/schoerob/Berkeley"
DAVIS_PATH: "/data/raid_ssd/schoerob/DAVIS"
COCO_MVAL_PATH: "/playpen-raid2/qinliu/data/COCO_MVal"
BraTS_PATH: "/data/raid_ssd/schoerob/BraTS20"
ssTEM_PATH: "/playpen-raid2/qinliu/data/ssTEM"
OAIZIB_PATH: "/data/raid_ssd/schoerob/OAI-ZIB"
OAI_PATH: "/playpen-raid2/qinliu/data/OAI"
HARD_PATH: "/playpen-raid2/qinliu/data/HARD"
SHSEG_PATH: "/data/raid_ssd/schoerob/SHSeg"
COCO_PATH: "/data/raid_ssd/schoerob/mscoco"

# Evaluations datasets that have been used in the SAM Paper
PPDLS_PATH: "/data/raid_ssd/schoerob/Plant_Phenotyping_Datasets/Plant_Phenotyping_Datasets"
BBBC038_PATH: "/data/raid_ssd/schoerob/BBBC038v1"
DOORS_PATH: "/data/raid_ssd/schoerob/DOORS/Segmentation"
TIMBERSEG_PATH: "/data/raid_ssd/schoerob/TimberSeg/prescaled"
NDD20_PATH: "/data/raid_ssd/schoerob/NDD20"
STREETS_PATH: "/data/raid_ssd/schoerob/STREETS_dataset/vehicleannotations/vehicleannotations"
ZerowasteF_PATH: "/data/raid_ssd/schoerob/zerowaste-f-final/splits_final_deblurred"
ISHAPE_PATH: "/data/raid_ssd/schoerob/ishape_dataset"
ADE20KSUB_PATH: "/data/raid_ssd/datasets/ADE20k/ADE20K_2021_17_01"
WSESEG_PATH: "/data/raid_ssd/schoerob/sports_tools"

# Train datasets
SBD_PATH: "/data/raid_ssd/schoerob/hq_depthseg/sbd"
HQSEG_PATH: "/data/raid_ssd/schoerob/hqseg44k"
#COCO_PATH: "/playpen-raid2/qinliu/data/COCO_2017"
LVIS_v1_PATH: "/data/raid_ssd/schoerob/cocolvis"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "/playpen-raid2/qinliu/data/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./weights/pretrained/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./weights/pretrained/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./weights/pretrained/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./weights/pretrained/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W64: "./weights/pretrained/hrnetv2_w64_imagenet_pretrained.pth"
  MIT_B5: "./weights/pretrained/mit_b5_converted.pth"
  MIT_B4: "./weights/pretrained/mit_b4_converted.pth"
  MIT_B3: "./weights/pretrained/mit_b3_converted.pth"
  MIT_B2: "./weights/pretrained/mit_b2_converted.pth"
  MIT_B1: "./weights/pretrained/mit_b1_converted.pth"
  MIT_B0: "./weights/pretrained/mit_b0_converted.pth"
  HRF_BASE: "./weights/pretrained/hrt_base.pth"
  SWIN_BASE: "./weights/pretrained/swin_base_patch4_window12_384_22k.pth"
  SWIN_LARGE: "./weights/pretrained/swin_large_patch4_window12_384_22k.pth"
  MAE_BASE: "/data/raid_ssd/schoerob/weights/mae/mae_pretrain_vit_base.pth"
  MAE_LARGE: "./weights/pretrained/mae_pretrain_vit_large.pth"
  MAE_HUGE: "./weights/pretrained/mae_pretrain_vit_huge.pth"

